version: '3'

volumes:
  mongodb: 
  experiments:
  redis:

services:
  netlyt:
    image: netlyt
    build:
      context: ./Netlyt
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo.netlyt.com 
    ports:
      - "5000:5000"
      - "81:80"
  
  jenkins:
    privileged: true
    build:
      context: ./docker/jenkins
      dockerfile: Dockerfile
      args:
        JENKINS_VERSION: 2.91
    container_name: jenkins
    restart: always  
    ports:
      - 8080:8080
    volumes:
      - ./jenkins:/var/jenkins_home

  redis:
    image: redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    container_name: redis.netlyt.com
    hostname: redis.netlyt.com
    ports:
      - 6399:6399
    volumes:
      - redis:/data

  mongo.netlyt.com :
    image: library/mongo:3.4
    hostname: mongo.netlyt.com 
    container_name: mongo.netlyt.com 
    volumes:
      - mongodb:/data/db
    ports:
      - "27019:27017"
    #So that we actually have auth enabled..
    #to setup a user, follow this https://stackoverflow.com/questions/22638258/create-superuser-in-mongo
    command: mongod --auth

  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "10.10.1.7:443:5000"
    volumes:
      - ./registry:/var/lib/registry
      - ./auth:/auth
      - ./auth:/certs
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/registry.netlyt.com"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/registry_auth.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/registry_auth.key"

      #-e VIRTUAL_HOST=registry.netlyt.com 
#-e LETSENCRYPT_HOST=registry.netlyt.com 
#-e LETSENCRYPT_EMAIL=vaskovasilev94@yahoo.com 
#--network=webproxy --name my_app httpd:alpine

  behaviour:
    container_name: behaviour.netlyt.com
    hostname: behaviour.netlyt.com
    build:
      context: ./BehaviorAnalysis
      dockerfile: Dockerfile
    volumes:
      - ./BehaviorAnalysis/src:/app
      - experiments:/experiments
    ports:
      - "5556:5556"
      - "5557:5557"

networks:
  default:
    external:
      name: webproxy
