version: '3'

volumes:
  mongodb: 
  experiments:
  redis:
  pgdata:
  pgdata_dev:

services:
  balancer:
    container_name: balancer
    build:
      context: ./haproxy
    ports:
      - "10.10.1.5:80:80"

#$ is escaped with $$
  netlyt:
    image: netlyt
    hostname: api.netlyt.io
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo.netlyt.io 
      - postgres
      - orion
      - balancer
    ports:
      - "5000:5000"
      - "81:80"
    environment:
      - MQ_HOST=mq.netlyt.io
      - MQ_PASS=rgwsoertkgpowrk$$
      - MQ_PORT=5672
      - MQ_USER=netlyt
      - NODE_TYPE=cloud


  rabbitmq:
    image: rabbitmq:3-management
    hostname: "loc.mq.netlyt.io"
    container_name: rabbitmq
    env_file:
      - rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    container_name: redis.netlyt.io
    hostname: redis.netlyt.io
    restart: always
    ports:
      - 6399:6399
    volumes:
      - redis:/data

  mongo.netlyt.io :
    image: library/mongo:3.4
    hostname: mongo.netlyt.io 
    container_name: mongo.netlyt.io 
    volumes:
      - mongodb:/data/db
    ports:
      - "27019:27017"
    #So that we actually have auth enabled..
    #to setup a user, follow this https://stackoverflow.com/questions/22638258/create-superuser-in-mongo
    command: mongod

  postgres_dev:
    image: postgres
    container_name: postgres_dev.netlyt.io
    hostname: postgres_dev.netlyt.io 
    restart: always
    env_file:
      - postgre_auth.env
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  postgres:
    image: postgres
    container_name: postgres.netlyt.io
    hostname: postgres.netlyt.io 
    restart: always
    env_file:
      - postgre_auth.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  orion:
    container_name: orion.netlyt.io
    hostname: orion.netlyt.io
    build:
      context: ./Orion
      dockerfile: Dockerfile
    volumes:
      - ./Orion/app:/app
      - ./Orion/experiments:/experiments
        #      - ./orion/automl:/opt/conda/lib/python3.6/site-packages/autosklearn
    ports:
      - "5556:5556"
      - "5557:5557"
      - "5560:5560"
      - "82:80"
    env_file:
      - orion.env
    
 
