version: '3'

volumes:
  mongodb: 
  experiments:
  redis:

services:
  peeralize:
    image: peeralize
    build:
      context: ./Peeralize
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo.peeralize.com 
    ports:
      - "5000:5000"
      - "80:80"
  
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./jenkins:/var/jenkins_home

  redis:
    image: redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    container_name: redis.peeralize.com
    hostname: redis.peeralize.com
    ports:
      - 6399:6399
    volumes:
      - redis:/data

  mongo.peeralize.com :
    image: library/mongo:3.4
    hostname: mongo.peeralize.com 
    container_name: mongo.peeralize.com 
    volumes:
      - mongodb:/data/db
    ports:
      - "27019:27017"
    #So that we actually have auth enabled..
    #to setup a user, follow this https://stackoverflow.com/questions/22638258/create-superuser-in-mongo
    command: mongod --auth

  behaviour:
    container_name: behaviour.peeralize.com
    hostname: behaviour.peeralize.com
    build:
      context: ./BehaviorAnalysis
      dockerfile: Dockerfile
    volumes:
      - ./BehaviorAnalysis/src:/app
      - experiments:/experiments
    ports:
      - "5556:5556"
      - "5557:5557"